plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = '0.13.1'
group = 'net.warcar.hito_hito_nika' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17) // Mojang ships Java 17 to end users (1.18+), so your mod should target Java 17.

println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))
minecraft {
    mappings channel: "parchment", version: "2023.09.03-1.20.1"
    copyIdeResources = true
    generateRunFolders = true
    
    // accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        // applies to all the run configs below
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        client {
            workingDirectory project.file('run/client')
            property 'forge.enabledGameTestNamespaces', mod_id
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }

        client2 {
            workingDirectory project.file('run/client2')
            args '--username', 'Dev3'
            property 'forge.enabledGameTestNamespaces', mod_id
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }

        server {
            workingDirectory project.file('run/server')
            property 'forge.enabledGameTestNamespaces', mod_id
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}
repositories {
    flatDir {
        dir 'libs'
    }
    maven {
        url "https://cursemaven.com"
    }
}
// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }
mixin {
    //add sourceSets.main, 'hito_hito_no_mi_nika.refmap.json'
    config 'hito_hito_no_mi_nika.mixin.json'

    debug.verbose = true
    debug.export = true
    dumpTargetOnFailure = true
}
dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-47.4.16"


    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation fg.deobf("curse.maven:mine-mine-no-mi-78726:8324322")
    //runtimeOnly fg.deobf("curse.maven:mine-mine-no-mi-haki-bar-650542:7824637")
    //implementation fg.deobf("blank:mine-mine-no-mi-${minecraft_version}:${mineminenomi_version}")
    //runtimeOnly fg.deobf("blank:cartaddon:0.7.5")
}

// Example for how to get properties into the manifest for reading by the runtime..
jar {
    manifest {
        attributes([
            "Specification-Title": "hito_hito_nika",
            "Specification-Vendor": "hito_hito_nikasareus",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "0.1",
            "Implementation-Vendor" :"hito_hito_nikasareus",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

// Example configuration to allow publishing using the maven-publish task
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar') 
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
//publish.dependsOn('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
